export const ASSETS = {
  bgFar: 'bgFar',
  bgMid: 'bgMid',
  bgNear: 'bgNear',
  crowIdle: 'crowIdle',
  crowFlap0: 'crowFlap0',
  crowFlap1: 'crowFlap1',
  crowFlap2: 'crowFlap2',
  crowDead: 'crowDead',
  obstacleTop: 'obstacleTop',
  obstacleBottom: 'obstacleBottom',
  ground: 'ground',
  ember: 'ember',
  vignette: 'vignette',
} as const

export const THEME = {
  assetPaths: {
    [ASSETS.bgFar]: 'assets/bg_far.svg',
    [ASSETS.bgMid]: 'assets/bg_mid.svg',
    [ASSETS.bgNear]: 'assets/bg_near.svg',
    [ASSETS.crowIdle]: 'assets/crow_idle.svg',
    [ASSETS.crowFlap0]: 'assets/crow_flap_0.svg',
    [ASSETS.crowFlap1]: 'assets/crow_flap_1.svg',
    [ASSETS.crowFlap2]: 'assets/crow_flap_2.svg',
    [ASSETS.crowDead]: 'assets/crow_dead.svg',
    [ASSETS.obstacleTop]: 'assets/obstacle_top.svg',
    [ASSETS.obstacleBottom]: 'assets/obstacle_bottom.svg',
    [ASSETS.ground]: 'assets/ground.svg',
    [ASSETS.ember]: 'assets/ember.svg',
    [ASSETS.vignette]: 'assets/vignette.svg',
  },
  ui: {
    fontFamily: '"Cinzel", "Trebuchet MS", serif',
    canvasBackground: '#0a0b12',
    scoreTextStyle: {
      fontFamily: '"Cinzel", "Trebuchet MS", serif',
      fontSize: '36px',
      color: '#d7f5ff',
      stroke: '#0b0d13',
      strokeThickness: 6,
    },
    overlayTextStyle: {
      fontFamily: '"Cinzel", "Trebuchet MS", serif',
      fontSize: '22px',
      color: '#d7f5ff',
      align: 'center',
      stroke: '#0b0d13',
      strokeThickness: 5,
    },
    panel: {
      width: 280,
      height: 120,
      fill: 0x0b0d13,
      fillAlpha: 0.75,
      stroke: 0x4dd6e3,
      strokeThickness: 2,
      grainAlpha: 0.12,
    },
    panelLarge: {
      width: 300,
      height: 140,
    },
  },
  parallax: {
    far: 0.08,
    mid: 0.18,
    near: 0.32,
  },
  particles: {
    embers: {
      enabled: true,
      count: 24,
      speedMin: 10,
      speedMax: 28,
      driftMin: -6,
      driftMax: 6,
      scaleMin: 0.25,
      scaleMax: 0.55,
      alphaMin: 0.2,
      alphaMax: 0.6,
      lifespanMin: 2400,
      lifespanMax: 5200,
      frequency: 650,
    },
  },
  vignette: {
    alpha: 0.55,
  },
} as const
