import type { EnvironmentConfig } from './types'

const V2_KEYS = {
  skyFar: 'v2-bg-sky-far',
  mountains: 'v2-bg-mountains',
  treesFar: 'v2-bg-trees-far',
  treesMid: 'v2-bg-trees-mid',
  swampNear: 'v2-bg-swamp-near',
  fgBranches: 'v2-fg-branches',
  fogSoft: 'v2-fog-soft',
  lightRays: 'v2-light-rays',
  waterMask: 'v2-water-mask',
  biolume: 'v2-biolume',
} as const

export const EVIL_FOREST_V2: EnvironmentConfig = {
  key: 'v2',
  label: 'Evil Forest V2',
  assets: [
    {
      key: V2_KEYS.skyFar,
      path: 'assets/theme/evil_forest_v2/bg_sky_far.png',
      pathWebp: 'assets/theme/evil_forest_v2/bg_sky_far.webp',
    },
    {
      key: V2_KEYS.mountains,
      path: 'assets/theme/evil_forest_v2/bg_mountains.png',
      pathWebp: 'assets/theme/evil_forest_v2/bg_mountains.webp',
    },
    {
      key: V2_KEYS.treesFar,
      path: 'assets/theme/evil_forest_v2/bg_trees_far.png',
      pathWebp: 'assets/theme/evil_forest_v2/bg_trees_far.webp',
    },
    {
      key: V2_KEYS.treesMid,
      path: 'assets/theme/evil_forest_v2/bg_trees_mid.png',
      pathWebp: 'assets/theme/evil_forest_v2/bg_trees_mid.webp',
    },
    {
      key: V2_KEYS.swampNear,
      path: 'assets/theme/evil_forest_v2/bg_swamp_near.png',
      pathWebp: 'assets/theme/evil_forest_v2/bg_swamp_near.webp',
    },
    {
      key: V2_KEYS.fgBranches,
      path: 'assets/theme/evil_forest_v2/fg_branches.png',
      pathWebp: 'assets/theme/evil_forest_v2/fg_branches.webp',
    },
    {
      key: V2_KEYS.fogSoft,
      path: 'assets/theme/evil_forest_v2/fog_tile_soft.png',
      pathWebp: 'assets/theme/evil_forest_v2/fog_tile_soft.webp',
    },
    {
      key: V2_KEYS.lightRays,
      path: 'assets/theme/evil_forest_v2/light_rays.png',
      pathWebp: 'assets/theme/evil_forest_v2/light_rays.webp',
    },
    {
      key: V2_KEYS.waterMask,
      path: 'assets/theme/evil_forest_v2/water_reflection_mask.png',
      pathWebp: 'assets/theme/evil_forest_v2/water_reflection_mask.webp',
    },
    {
      key: V2_KEYS.biolume,
      path: 'assets/theme/evil_forest_v2/biolume_glow_splotches.png',
      pathWebp: 'assets/theme/evil_forest_v2/biolume_glow_splotches.webp',
    },
  ],
  layers: [
    { key: V2_KEYS.skyFar, name: 'Sky Far', speed: 0.02, depth: 0 },
    { key: V2_KEYS.mountains, name: 'Mountains', speed: 0.035, depth: 0.12 },
    { key: V2_KEYS.treesFar, name: 'Trees Far', speed: 0.055, depth: 0.24 },
    { key: V2_KEYS.treesMid, name: 'Trees Mid', speed: 0.085, depth: 0.42 },
    { key: V2_KEYS.swampNear, name: 'Swamp Near', speed: 0.14, depth: 0.66 },
  ],
  fogLayers: [
    {
      key: V2_KEYS.fogSoft,
      name: 'Fog A',
      speed: 0.02,
      depth: 0.3,
      alpha: 0.2,
      scale: 1.1,
      blendMode: 'normal',
    },
    {
      key: V2_KEYS.fogSoft,
      name: 'Fog B',
      speed: 0.045,
      depth: 0.6,
      alpha: 0.26,
      scale: 1.18,
      blendMode: 'normal',
    },
  ],
  foregroundLayers: [
    {
      key: V2_KEYS.fgBranches,
      name: 'Branches',
      speed: 0.18,
      depth: 0.84,
      alpha: 0.35,
    },
  ],
  lightRays: {
    key: V2_KEYS.lightRays,
    depth: 0.5,
    alpha: 0.08,
    pulseSpeed: 0.6,
    scale: 1,
    blendMode: 'screen',
  },
  reflection: {
    maskKey: V2_KEYS.waterMask,
    depth: 0.58,
    waterlineY: 380,
    height: 200,
    rippleSpeed: 0.6,
    rippleAmplitude: 3,
    layers: [
      { key: V2_KEYS.treesMid, speed: 0.085, alpha: 0.14 },
      { key: V2_KEYS.swampNear, speed: 0.14, alpha: 0.18 },
    ],
  },
  biolume: {
    key: V2_KEYS.biolume,
    depth: 0.72,
    blendMode: 'add',
    patches: [
      { x: 160, y: 440, scale: 0.62, alpha: 0.36, pulseSpeed: 0.9 },
      { x: 320, y: 480, scale: 0.72, alpha: 0.4, pulseSpeed: 0.7 },
      { x: 520, y: 450, scale: 0.68, alpha: 0.36, pulseSpeed: 0.8 },
      { x: 720, y: 490, scale: 0.76, alpha: 0.4, pulseSpeed: 0.75 },
    ],
  },
  lowPower: {
    disableFog: true,
    disableForeground: true,
    disableLightRays: true,
    disableReflection: true,
    disableBiolume: true,
    disableLayers: ['Trees Mid', 'Swamp Near'],
  },
  particles: {
    embers: {
      enabled: true,
      frequency: 2400,
      maxParticles: 6,
      speedMin: 6,
      speedMax: 12,
      driftMin: -4,
      driftMax: 4,
      scaleMin: 0.18,
      scaleMax: 0.35,
      alphaMin: 0.08,
      alphaMax: 0.22,
      lifespanMin: 1800,
      lifespanMax: 3200,
      tint: 0xffa46a,
      blendMode: 'add',
    },
    dust: {
      enabled: true,
      frequency: 1500,
      maxParticles: 18,
      speedMin: 2,
      speedMax: 8,
      driftMin: -3,
      driftMax: 3,
      scaleMin: 0.2,
      scaleMax: 0.4,
      alphaMin: 0.08,
      alphaMax: 0.2,
      lifespanMin: 2200,
      lifespanMax: 5200,
      blendMode: 'normal',
    },
    leaf: {
      enabled: false,
      frequency: 2400,
      maxParticles: 6,
      speedMin: 6,
      speedMax: 12,
      driftMin: -6,
      driftMax: 6,
      scaleMin: 0.2,
      scaleMax: 0.35,
      alphaMin: 0.1,
      alphaMax: 0.2,
      lifespanMin: 2400,
      lifespanMax: 4800,
      blendMode: 'normal',
    },
    fireflies: {
      enabled: true,
      frequency: 900,
      maxParticles: 14,
      speedMin: 4,
      speedMax: 10,
      driftMin: -4,
      driftMax: 4,
      scaleMin: 0.18,
      scaleMax: 0.35,
      alphaMin: 0.2,
      alphaMax: 0.6,
      lifespanMin: 1800,
      lifespanMax: 3200,
      tint: 0xb56bff,
      blendMode: 'add',
      areas: [
        { x: 80, y: 400, width: 180, height: 120 },
        { x: 260, y: 430, width: 180, height: 140 },
        { x: 460, y: 410, width: 200, height: 140 },
        { x: 660, y: 430, width: 200, height: 140 },
      ],
    },
  },
}
