export const FX = {
  parallax: {
    far: 0.06,
    mid: 0.16,
    near: 0.3,
  },
  fog: {
    speedX: 6,
    alpha: 0.32,
  },
  obstacleSway: {
    amplitude: 0.035,
    speed: 0.0026,
  },
  embers: {
    enabled: true,
    frequency: 700,
    count: 26,
    speedMin: 12,
    speedMax: 28,
    driftMin: -6,
    driftMax: 6,
    scaleMin: 0.25,
    scaleMax: 0.6,
    alphaMin: 0.2,
    alphaMax: 0.55,
    lifespanMin: 2400,
    lifespanMax: 5200,
  },
  dust: {
    enabled: true,
    frequency: 1200,
    count: 20,
    speedMin: 4,
    speedMax: 10,
    driftMin: -4,
    driftMax: 4,
    scaleMin: 0.18,
    scaleMax: 0.4,
    alphaMin: 0.08,
    alphaMax: 0.22,
    lifespanMin: 2600,
    lifespanMax: 6200,
  },
  leaf: {
    enabled: true,
    frequency: 1800,
    count: 12,
    speedMin: 8,
    speedMax: 16,
    driftMin: -8,
    driftMax: 8,
    scaleMin: 0.25,
    scaleMax: 0.5,
    alphaMin: 0.18,
    alphaMax: 0.4,
    lifespanMin: 2400,
    lifespanMax: 5200,
  },
  scorePulse: {
    scale: 1.08,
    duration: 120,
  },
  screenShake: {
    duration: 140,
    intensity: 0.002,
  },
  cameraPunch: {
    enabled: true,
    amount: 0.02,
    durationMs: 120,
  },
  sceneFade: {
    enabled: true,
    durationMs: 220,
  },
  overlayBounce: {
    enabled: true,
    startScale: 0.96,
    durationMs: 260,
  },
  screenFlash: {
    enabled: true,
    color: 0xffffff,
    alpha: 0.18,
    durationMs: 140,
  },
  impactBurst: {
    enabled: true,
    count: 14,
    speedMin: 80,
    speedMax: 170,
    scaleMin: 0.35,
    scaleMax: 0.7,
    alphaStart: 0.9,
    alphaEnd: 0,
    lifespanMin: 320,
    lifespanMax: 520,
    tint: 0xffd4a8,
  },
  vignette: {
    alpha: 0.6,
  },
  readyBob: {
    amplitude: 6,
    speed: 2.6,
  },
} as const
